global:
  scrape_interval: 15s # Собирать метрики каждые 15 секунд

scrape_configs:
  - job_name: 'dss-app'
    metrics_path: '/actuator/prometheus' # Эндпоинт, который мы включили
    static_configs:
      - targets: ['dss-app:8080'] # 'dss-app' - это имя нашего сервиса в docker-compose